owner: redbing-srl
repo: redbing-diagnosee-uptime

sites:
  - name: Diagnosee - Web App
    url: https://app.diagnosee.com
  - name: Diagnosee - Auth
    url: https://app.diagnosee.com/api/auth-health
  - name: Diagnosee - API
    url: https://app.diagnosee.com/api/trpc/health.db

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /redbing-diagnosee-uptime
  name: Diagnosee Status
  introTitle: "**Diagnosee** platform status"
  introMessage: Real-time uptime of the Diagnosee production environment (web app, API, auth).
  navbar:
    - title: Status
      href: /redbing-diagnosee-uptime
    - title: GitHub
      href: https://github.com/redbing-srl/redbing-diagnosee-uptime

# Notifications, issue assignment, and more: https://upptime.js.org/docs/configuration
# Change these first
